blank_issues_enabled: true
contact_links:
  - name: Aroma Discord
    url: https://discord.com/invite/bZ2rep2
    about: Join the Aroma Discord to interact with the Wii U Homebrew community.
  - name: Rust-Lang Discord
    url: https://discord.gg/rust-lang-community
    about: Join the Rust Discord to interact with the Rust community.
