blank_issues_enabled: true
contact_links:
  - name: Discord aRAMa
    url: https://discord.com/invite/VPHr56hnbQ
    about: Join our Discord server to directly interact with the community to ask questions and get help.
